### ISSUE TITLE
403 installing components

### ISSUE THREAD

**Issue by flaviocordova** [craftship/codebox-npm#102]
I'm trying to setup the application and followed all the steps, but I'm not being able to execute npm install because I get a 403 (forbidden) all the time..

I've got to run npm login but can't go any further because of this.. apparently all the settings are ok (I've checked the variables in aws console) and I'm stuck now...

Is there any checklist I could use to try to find where it's failing ?

Thanks a lot !

**Comment by jonsharratt** [comment]
This maybe related to https://github.com/craftship/codebox-npm/issues/101#issuecomment-374407250 - could you possibly take a look and see if this resolves your problem also.

**Comment by jonsharratt** [comment]
Closing this for now, please do try the mentioned steps and re-open if this is still an issue.

Thanks!
