### ISSUE TITLE
Checksum fail when downloading as another user

### ISSUE THREAD

**Issue by hassankhan** [craftship/codebox-npm#35]
# This is a Bug Report

## Description
I've published a package on Yith under my username, elsewhere my colleague has logged in and tries to download the package.

For bug reports:
* What went wrong?
It failed with a checksum error.

* What did you expect should have happened?
It should have downloaded the dependency as usual.

* What stacktrace or error message did you
experience?
```
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node@6/6.9.5/bin/node" "/usr/local/bin/npm" "i" "-S" "yith-test"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10

npm ERR! shasum check failed for /var/folders/hy/5mcsh4rj4nqdr2dd7lsfzybr0000gn/T/npm-44837-8db82cdb/wgn99rpqrc.execute-api.eu-west-1.amazonaws.com/prod/registry/yith-test/-/yith-test-1.0.1.tgz
npm ERR! Expected: e4ef8ff55c945d69986138d3d390c41d1841cf9a
npm ERR! Actual:   298b1fe737fc503f48bc89e36ad063615bf9fc04
npm ERR! From:     https://wgn99rpqrc.execute-api.eu-west-1.amazonaws.com/prod/registry/yith-test/-/yith-test-1.0.1.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/hassankhan/Projects/yith-project-test/npm-debug.log
```

## Additional Data

* ***NPM CLI version you are using***: 3.10.10
* ***Serverless version you're using***: 1.6.1
* ***Node version you're using***: 6.9.5

**Comment by jonsharratt** [comment]
That is a interesting one, I only ever had this issue when the `contentHandling` was incorrectly setup in Amazon API Gateway for the `GET tar` endpoint.  The `.serverless_plugin` contentHandling plugin should deal with this accordingly.

When you deployed was it from master or the tag `0.7.0`.

**Comment by hassankhan** [comment]
From `master`. Might be a good idea to put the Yith version in the issue templates as well.

**Comment by jonsharratt** [comment]
Agreed, will do a quick test and get back to you to see if I can reproduce.

**Comment by jonsharratt** [comment]
Ok, can you confirm the other user has done an `npm login` successfully.  This may need some better handling.

Just tried `0.7.0`, which uses serverless `1.5.1` and it worked correctly.  Used Charles to confirm the response.

![image](https://cloud.githubusercontent.com/assets/430934/22748599/78987cba-ee22-11e6-84ee-ba15017d732b.png)

Would think master will be fine as not changed much, if any functionallity.  Only thing I can think of is the error is returned as the base64 response saying that user was not authenticated.

Will try master just now and report back again.

**Comment by jonsharratt** [comment]
Can also confirm `master` works for myself on node `6.9.5`, serverless `1.6.1` and npm `3.10.10`, so three things to check:

1) Other user has done a `npm login` successfully.
2) Other user can confirm `npm get registry` is set to the correct url of deployed registry.
3) What was the package name you published and does the name exist on npm?  It may well be something to do with this case, there is a feature to check npm first to ensure you do not have the ability to override a pubic package name as that could lead to confusion / security implications.

Would try just publishing / setting your name in package.json with a scope (e.g. `@unique-org/package-name`) or make it unique to public npm also, then get the other user to try an `npm install` of that package.

Best to use an `.npmrc` file per repo to save switching manually as will get rather annoying.

Let me know how you get on :)

**Comment by hassankhan** [comment]
1. Other user has logged in successfully (checked in `.npmrc` for the auth token)
2. Other user can run `npm get registry` successfully
3. The name I published was `argo-serverless-common`, the name does not exist on the NPM registry (at least from my search)

I can definitely try publishing with a scope, will try and report back. 

I was using a global `.npmrc` for the moment, with empty `.npmrc` in the projects (for the CI stuff). Should I do it differently?

**Comment by jonsharratt** [comment]
We tend to just set `.npmrc` with just the `registry=https://registryurl` per repo then for CI append the URL with npm auth token from environment variables using `echo`.

Allows it to auto switch back to the public one when you are doing personal or other projects

**Comment by hassankhan** [comment]
I tried publishing with under a scope, again it published successfully, I can download it successfully on my own machine but it refuses to on another machine with another user.

If it makes any difference, I published using npm version 3.10.3 and Node version 6.7.0

**Comment by jonsharratt** [comment]
Is quite a hard one to debug, you can grab me on https://craftship-slack.herokuapp.com to join our Slack channel.  Alternatively might be useful to screen hero, then lastly if you are based in London and prefer I could even pop over one Friday to try and crack what the issue is with this one.

One quick thing to try is a `npm cache clean` before trying the `npm install` again.

A more involved step if you have Charles is that you could try and log to see the requests and response data for the `npm install` but it requires a few steps:
* Trust the  Charles SSL certificate (In Charles `Help > SSL proxying > Install Charles Root Certificate`)
* Trust your domain in `SSL Proxy` options of Charles (In Charles `Proxy > SSL proxying settings... > Enable SSL Proxying > Add (your hostname and port 443 for the registry deployed)`)
* Disable strict SSL `npm config set strict-ssl false`
* `npm set proxy http://localhost:8888`
* Record in Charles and try to `npm install` the package

If you can post as much detail as possible for the requests and responses against the registry, then remember to:
* Re-enable strict SSL `npm config set strict-ssl true`
* Unset proxy `npm config delete proxy`

We will crack this 👍

**Comment by hassankhan** [comment]
Thanks @jonsharratt, might have to meet up one Friday then 😄 . I'll try running `npm cache clean` again and report back.

**Comment by jonsharratt** [comment]
Let me know if you are still having issues with this, would be good to get this closed off, additionally released 0.8.0 which I will sort a logger out for CloudWatch just in case there are errors being thrown on the tar endpoint - else if you have slack you could setup the experimental slack logger that would post any errors and stack trace into a channel you specify.

**Comment by hassankhan** [comment]
Sorry hadn't had a chance, will test with v0.8.0 and report back.

**Comment by jonsharratt** [comment]
Closing this one for now, had other users confirm things seem to be all well when doing a clean setup.  Please do let me know if you still have issues and re-open, more than happy to help out.

**Comment by hassankhan** [comment]
I'm sorry, been swamped with work, will give it a go for sure tomorrow and will post back!
