### ISSUE TITLE
Use yith with Gitlab

### ISSUE THREAD

**Issue by amiceli** [craftship/codebox-npm#45]
# This is a question

## Description

Have you planned to make yith compatible with Gitlab ?

**Comment by jonsharratt** [comment]
Hey @amiceli thanks for the question, you could no doubt switch out the `user/put.js` function and replace the custom authoriser to integrate with GitLab instead, there is no immediate plan just now to do that piece of work.

That said I will add it to the backlog, it would probably end up being a plugin for switchable authentication strategies that could be selected upon doing a `serverless install` command.  

Depends on how many others would like this support. 👍

**Comment by jonsharratt** [comment]
So just for those that are interested, multi-security provider support is on our backlog.  Will keep this thread updated once I can share more on progress with this.

**Comment by amiceli** [comment]
Sorry for the delay.
Thanks for your answer, I'll check `user/put.js` file.

**Comment by jonsharratt** [comment]
So been looking at features in the pipeline, at the moment the priority will be multi-cloud provider and then multi-auth support.

Let me know if you give it a go, more than happy to support you where I can to get this feature in.

**Comment by mytototo** [comment]
Hi there, any news regarding the multi-auth support? This project is really a component I could use but I'm not using GitHub for node modules.... GitLab and/or Bitbucket could be a very interesting feature.
