### ISSUE TITLE
Clarification on CI Setup

### ISSUE THREAD

**Issue by hassankhan** [craftship/codebox-npm#57]
In the [README](https://github.com/craftship/codebox-npm/blame/master/README.md#L90) it seems to be saying add the token without the `//` prefix, is that correct or just an oversight?

**Comment by jonsharratt** [comment]
Heya, the README is correct, the login URL does not require the prefix and should be omitted.

This is based on a teams current setup we have across the entire deployment pipeline, watch this space for some better and easier to follow docs.

**Comment by hassankhan** [comment]
Wicked, thanks for the confirmation 👍
