### ISSUE TITLE
Codebox not recognized as command to migrate to custom domain.

### ISSUE THREAD

**Issue by hixme-technology** [craftship/codebox-npm#61]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
   Command to migrate packages already deployed fails.  Command is not recognized.
   
   `serverless codebox domain --stage yourstage --host custom-domain.com`

   I see the source for the plugin in the .serverless folder, but regardless of how I structure the above      command, I receive the following error.

    `Serverless Error ---------------------------------------
      Command "codebox domain" not found, Run "serverless`

  Expecting an error, if I omit the domain I get the following:

    `  Serverless Error ---------------------------------------
     The command you entered did not catch on any hooks`

* What was the config / env variables you used?
  All CODEBOX_ environment variables are present and I am running the above command from the root of the codebox serverless repo

**Comment by jonsharratt** [comment]
Interesting, not 100% sure what is wrong here, checked the tagged releases and it appears to be configured and 'should' work.

Worth double checking that in your `serverless.yml` at the top of the file the plugins ar configured correctly, it should look like:

```
frameworkVersion: '=1.8.0'

plugins:
  - environment-variables
  - remove-storage
  - serverless-webpack
  - log-topic
  - content-handling
  - codebox-tools
```

`codebox-tools` being the important one in this case.  The other thing to check is when you run the `serverless` command in the root of your project does it list the command as being available, you should see it as the last command option:

![image](https://cloud.githubusercontent.com/assets/430934/24070567/1789bfd4-0bb8-11e7-8486-e8958e6073b5.png)

Presume you are using serverless version `1.8.0` ?

**Comment by hixme-technology** [comment]
The plugins are configured as you have shown.  I do have serverless version 1.8.0 and "codebox domain" is listed as an available command.

**Comment by jonsharratt** [comment]
Really not sure what is happening here, very odd, would be more than happy to screen hero with you to try and resolve or you can grab me on slack:

Can join our slack here:
http://craftship-slack.herokuapp.com/

Would be great to get you up and running 👍

**Comment by jonsharratt** [comment]
Closing this issue as managed to screen hero and sort this out directly with @hixme-technology on slack.

🎉 🍾
