### ISSUE TITLE
Two-factor authentication

### ISSUE THREAD

**Issue by DaleLJefferson** [craftship/codebox-npm#65]
# This is a (Bug Report / Feature Proposal)
Feature Proposal

## Description

Our Github organisation uses Github's two-factor authentication, I assumed I would be able to create a personal access token and use that in place of my password but I get the following error.

```json
{"message":"This API can only be accessed with username and password Basic Auth","documentation_url":"https://developer.github.com/v3/oauth_authorizations/#oauth-authorizations-api"}
```

If I use my real password I get

```json
{"message":"Must specify two-factor authentication OTP code.","documentation_url":"https://developer.github.com/v3/auth#working-with-two-factor-authentication"}
```

## Additional Data

* npm 4.2.0
* serverless 1.9.0
* node 6.10.1

**Comment by DaleLJefferson** [comment]
Sorry did not read the documentation

**Comment by jonsharratt** [comment]
No worries, if you have any further issues let me know 👍
