### ISSUE TITLE
Clarifications on how to use CODEBOX_RESTRICTED_ORGS.

### ISSUE THREAD

**Issue by ganapativs** [craftship/codebox-npm#70]
# Feature usage info needed

I have tried to restrict organisation using ```export CODEBOX_RESTRICTED_ORGS="xyzOrg"```  and ```export CODEBOX_GITHUB_URL="https://api.github.com/"``` and provided github tokens(from https://github.com/settings/developers) from same org. 

Tried logged in(using npm login) from github organisation email. but serverless url throws 403 for all the requests. 

If I remove ```CODEBOX_RESTRICTED_ORGS```, everything works fine. 

Need more clarifications on how to properly use ```CODEBOX_RESTRICTED_ORGS```?

## Additional Data

* ***NPM CLI version you are using - 4.2.0***:
* ***Serverless version you're using - 1.11.0***:
* ***Node version you're using - 7.8.0***:

**Comment by jonsharratt** [comment]
Could you try and set `CODEBOX_RESTRICTED_ORGS` again, there is sometimes depending on your organization settings the requirement for users to go to at https://github.com/settings/applications, find the app and then ensure your has granted access to read for that org.

If this is the case and all works I will update the docs as suggested. 

The scoping as far as I can see looks to be working correctly.

Let me know how you get on.

**Comment by ganapativs** [comment]
My bad, Looks like its working, the issue was with token & I was provided with wrong organisation token. 

This thing is awesome. Thanks for making it open source.
