### ISSUE TITLE
npm logout & unpublish - 403

### ISSUE THREAD

**Issue by ganapativs** [craftship/codebox-npm#71]
# Bug Report

```npm logout``` throws Registry returned 403 for DELETE on https://abcdefg12345.execute-api.us-east-1.amazonaws.com/prod/registry/-/user/token/4b72ca7212dec3de8bc4520de2275c112401312b

It should have logged out user from npm for default scope.

logs:
```
npm logout
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "logout"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code E403

npm ERR! Registry returned 403 for DELETE on https://abcdefg12345.execute-api.us-east-1.amazonaws.com/prod/registry/-/user/token/4b72ca7212dec3de8bc4520de2275c112401312b
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/user/.npm/_logs/2017-04-20T12_04_54_670Z-debug.log

```

Also I see similar issue while using ```npm unpublish @org/test@1.0.0 ```
(Registry returned 403 for DELETE on https://abcdefg12345.execute-api.us-east-1.amazonaws.com/prod/registry/@org%2ftest/-rev/undefined).

Any idea how to fix this?

## Additional Data

* ***NPM CLI version you are using - 4.2.0***:
* ***Serverless version you're using - 1.11.0***:
* ***Node version you're using - 7.8.0***:

**Comment by jonsharratt** [comment]
We currently don't have this endpoint implemented.  I shall look to get this in tomorrow.

**Comment by ganapativs** [comment]
Perfect! Thanks 👍

**Comment by ganapativs** [comment]
@jonsharratt If possible also add support for ```npm whoami```?

**Comment by jonsharratt** [comment]
Hey @ganapativs so `logout` and `whoami` is now supported in the latest version if you install it and re-deploy `0.18.0`.

As far as `unpublish` is concerned as it is bad practice to remove any packages that have been published, currently taking the standpoint to not to implement this functionality.

Currently the recommendation is to use `npm deprecate` which is implemented.

If you really do need to get rid of a package the easiest thing to do is have a policy that the AWS administrator goes in and deletes it from S3 manually ensuring consumers are aware of this.

Thanks for all the feedback, do me know if you have any further issues or ideas.

**Comment by ganapativs** [comment]
@jonsharratt Awesome. Thank you 👍👍
