### ISSUE TITLE
Disable function versioning by default

### ISSUE THREAD

**Issue by ganapativs** [craftship/codebox-npm#78]
## Description
Can we add ```versionFunctions: false``` option in serverless.yml? this option is ```true``` by default in serverless. so, this will create new function versions for each new deployment, which increases code storage in Lambda, so the cost.

I think mostly versioning is not required in registry by default.

Pull request - https://github.com/craftship/codebox-npm/pull/77

## Additional Data

* ***NPM CLI version you are using - 4.2.0***:
* ***Serverless version you're using - 1.11.0***:
* ***Node version you're using - 7.8.0***:

**Comment by jonsharratt** [comment]
See comment in #77 in regards to our thoughts on this one. 👍

**Comment by ganapativs** [comment]
@jonsharratt Yeah, but for me it the lambda storage was growing extremely fast as I was trying out deployment with different configs/versions. So I had to disable versionFunctions. For single deployment this shouldn't be a problem. Thanks for this awesome thingy 👍

P.S: sent you a mail with address to craftship.io email, Thanks.
