### ISSUE TITLE
Latest tag is always updated on npm publish

### ISSUE THREAD

**Issue by mjalkio** [craftship/codebox-npm#80]
# This is a Bug Report

## Description

The `latest` tag is always updated when running `npm publish`, even when specifying another tag using the `--tag` flag. This is not the expected behavior (see additional data).

I believe this can fixed by deleting line 69 (`json['dist-tags'].latest = version;`) in `publish.js`, but I'm not entirely sure whether there are assumptions in this code that I'm not aware of.

## Additional Data

* [NPM documentation on tags](https://docs.npmjs.com/getting-started/using-tags)
* [Prereleases and Npm](https://medium.com/@mbostock/prereleases-and-npm-e778fc5e2420)

**Comment by jonsharratt** [comment]
Thanks for reporting this one, I will take a look at this and let you know.

**Comment by jonsharratt** [comment]
Hey @mjalkio - applied and tested the fix, tagged and released! `0.20.1`💃 

As a thanks let me know your office address and will send you over some stickers for you and your team.

👍

**Comment by mjalkio** [comment]
Thanks for the quick fix @jonsharratt, I'll email you.

**Comment by jonsharratt** [comment]
@mjalkio Got your email, stickers are in the post on the way to you 👍
