### ISSUE TITLE
How to upgrade from older version?

### ISSUE THREAD

**Issue by hassankhan** [craftship/codebox-npm#85]
# This is a Feature Proposal

## Description

Is there a recommended way of upgrading from an older version? 

Installing using the instructions results in a copy of this repo without any Git history, so would it be better for us to clone the repo and deploy instead?

**Comment by jonsharratt** [comment]
You should just be able to update to latest tag version / re-clone and away you go.  That is how I have been doing upgrades, I also do this within a Docker container.
