### ISSUE TITLE
Cannot npm login using custom domain

### ISSUE THREAD

**Issue by snajjar** [craftship/codebox-npm#96]
# This is a Bug Report?
Bug? / Misconfiguration? / Lacking doc?

## Description

After deploying a serverless application (following the tutorial), and configuring my .npmrc to the following:
    
    registry=https://XXXX.execute-api.eu-central-1.amazonaws.com/prod/registry
    always-auth=true

I manage to login correctly

But npm login fails with the appropriate configuration:

    registry=https://my.custom.domain.com/prod/registry
    always-auth=true

## Additional Data

- When checking https://my.custom.domain.com/prod/registry on my browser, it works correctly
- https is working too and the certificate is valid
- when running the serverless command to migrate (serverless codebox domain --stage prod --host my.custom.domain.com), i get "Access denied"

* ***NPM CLI version you are using***:
npm 5.5.1

* ***Serverless version you're using***:
serverless 1.11.0

* ***Node version you're using***:
node 8.9.1

**Comment by snajjar** [comment]
Okay, enabling 2FA seems to solve the issue...

**Comment by snajjar** [comment]
I tried today to use a root domain instead of a subdomain, but the result is the same.

**Comment by snajjar** [comment]
Okay, I eventually figured it out.
I post it here, it may help someone else.

When mapping your ACM certificate (from your exact domain/subdomain) in API Gateway, you want to leave the path and step clear, don't map it to your phase (say "prod"). That was the issue for me (but I still don't understand why).

**Comment by jonsharratt** [comment]
Do you remember if you perhaps added a `/` when setting the registry url at some point.  Wondering if this maybe the case (see: https://github.com/craftship/codebox-npm/issues/101#issuecomment-374407250).  If not I will need to dig into this one a bit further.

Please do re-open if not 👍 - thanks for reporting!
