### ISSUE TITLE
The Serverless version does not satisfy the "frameworkVersion" in serverless.yml

### ISSUE THREAD

**Issue by tvb** [craftship/codebox-npm#99]
Following the steps from the README.md and finally running `serverless deploy --stage prod` results into:

> The Serverless version (1.25.0) does not satisfy the "frameworkVersion" (=1.11.0) in serverless.yml

Changing the serverless.yml line #1 into:
```
frameworkVersion: '=1.25.0'
```
fixes the error.

**Comment by cthos** [comment]
I ran into this too, but I noticed there's a later version of the framework. If you install from master:

`serverless install --url https://github.com/craftship/codebox-npm --name my-npm-registry`

Or from the latest tag:

`serverless install --url https://github.com/craftship/codebox-npm/tree/0.21.2 --name my-npm-registry`

It should be fixed there. (as it was changed to `frameworkVersion: '>=1.20.2'`)

**Comment by jonsharratt** [comment]
As mentioned by @cthos (thanks!) the above should hopefully resolve the issue seen, please do re-open if you are still seeing issues.
